sudo: false
language: python
python:
  - "3.5"
  - "3.6"
# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
# commands to install dependencies
install:
  - pip install -q pytest flake8 pip>=10 tox-travis
  - pip install -r requirements.txt
# command to run tests
script:
  - tox
  - tox -e lint
