---
origin_keys:
  ceph: source
  ceph-mon: source
  ceph-osd: source
  ceph-radosgw: source

# Main OpenStack services to be upgraded
# Services are upgraded in the order specified
# The order of services is based on:
# https://github.com/openstack-charmers/openstack-charms-tools/blob/master/os-upgrade.py
# https://docs.openstack.org/charm-guide/latest/1708.html
services:
  # Ceph
  - 'ceph-mon'
  - 'ceph-osd'
  - 'ceph-radosgw'

  # Identity
  - 'keystone'

  # Image
  - 'glance'

  # Nova
  - 'nova-cloud-controller'
  - 'nova-compute'

  # Neutron upgrades
  - 'neutron-api'
  - 'neutron-gateway'
  - 'neutron-openvswitch'

  # Backend block-storage upgrade.
  # Note: just upgrade cinder service.
  - 'cinder'
  - 'cinder-warmceph'

  # Upgrade dashboard
  - 'openstack-dashboard'

  - 'rabbitmq-server'

  - 'mysql'

add_services:
  - 'ceph-mon-nrpe'
  - 'ceph-osd-nrpe'
  - 'ceph-radosgw-hacluster'
  - 'ceph-radosgw-nrpe'
  - 'keystone-nrpe'
  - 'keystone-hacluster'
  - 'glance-nrpe'
  - 'glance-hacluster'
  - 'nova-cloud-controller-nrpe'
  - 'nova-cloud-controller-hacluster'
  - 'nova-compute-nrpe'
  - 'neutron-api-nrpe'
  - 'neutron-api-hacluster'
  - 'neutron-gateway-nrpe'
  - 'cinder-nrpe'
  - 'cinder-hacluster'
  - 'openstack-dashboard-nrpe'
  - 'openstack-dashboard-hacluster'
  - 'rabbitmq-server-nrpe'
  - 'mysql-nrpe'
  - 'mysql-hacluster'
  - 'ntp'
