name: Upload Python Package

on:
  create:
    tags:
      - refs/tags/*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install setuptools wheel twine
    - name: Build
      run: python setup.py sdist bdist_wheel
    - name: Publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        echo "check: ${GITHUB_REF} - $(cat VERSION)"
        [[ "${GITHUB_REF}" =~ refs/tags/$(cat VERSION) ]] && twine upload dist/* || echo "not publishing"
      shell: bash
