name: Upload Snap Package

on: push
# on:
#   create:
#     tags:
#       - refs/tags/*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - name: Install Snapcraft
      uses: samuelmeuli/action-snapcraft@v1
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install tox
    - name: Render snapcraft config
      run: |
        export SNAPCRAFT_PROJECT_VERSION=$(cat VERSION)
        envsubst < snap/snapcraft.yaml.tpl > snap/snapcraft.yaml
        rm snap/snapcraft.yaml.tpl
    - name: Build snap
      run: |
        sg lxd -c 'snapcraft --use-lxd'
        export SNAP_PATH="jujuna_$(cat VERSION)_amd64.snap"
        ls $SNAP_PATH

    - uses: actions/upload-artifact@v2
      with:
        name: jujuna.snap
        path: ${{ env.SNAP_PATH }}

      # https://circleci.com/docs/2.0/build-publish-snap-packages/
    - name: Publish snap
      run: |
        mkdir .snapcraft
        echo $SNAPCRAFT_TOKEN | base64 --decode --ignore-garbage > .snapcraft/snapcraft.cfg
        snapcraft push *.snap --release edge
      # [[ "${GITHUB_REF}" =~ refs/tags/$(cat VERSION) ]] && snapcraft push *.snap --release edge || echo "not publishing"
      shell: bash
